name: AutoBuild
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: "Build & test"
        run: |
          sudo apt install -y mingw-w64
          i686-w64-mingw32-c++ -o decryptcpuu.exe decryptcpuu.cpp -Wall -static
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: binary
          path: decryptcpuu.exe
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: decryptcpuu.exe
